FROM golang:1.23.4-alpine AS build-stage

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /receipt-processor-challenge

FROM gcr.io/distroless/base-debian11 AS build-release-stage

WORKDIR /

COPY --from=build-stage /receipt-processor-challenge /receipt-processor-challenge

EXPOSE 3000

USER nonroot:nonroot

ENTRYPOINT [ "/receipt-processor-challenge" ]